name: PrincipalPlugin
version: '${version}'
main: fr.silenthill99.principalplugin.Main
api-version: 1.16
authors: [ silenthill99 ]

depend: [ Vault, WorldGuard ]

softdepend: [ LuckPerms ]

commands:
  action:
  administrateur:
    aliases: admin
    permission: oxydia.admin
    permission-message: §4Seul les administrateurs peuvent faire cette commande !
  aide:
    aliases: a
    description: Commande permettant de demander de l'aide à un membre du staff
  builder:
    permission: oxydia.builder
    permission-message: §4Seuls les builders peuvent faire cette commande !
  co-fondateur:
    aliases: [cofondateur, co-fonda, cofonda]
    permission: oxydia.cofonfateur
    permission-message: §4Seuls les co-fondateurs peuvent faire cette commande !
  developpeur:
    aliases: dev
    permission: oxydia.developpeur
    permission-message: §4Seuls les développeurs peuvent faire cette commande !
  fondateur:
    aliases: fonda
    permission: oxydia.fondateur
    permission-message: §4Seul le fondateur peut faire cette commande !
  hrp:
  kit:
  logs:
    permission: group.modo-stagiaire
  maire:
    description: Commande pour le maire !
    permission: group.maire
    permission-message: §4Seul le maire peut faire cette commande !
  menu:
    permission: group.modo-stagiaire
    permission-message: §4Vous n'avez pas accès à ceci !
  moderateur:
    aliases: modo
    permission: oxydia.modo
    permission-message: §4Seuls les modérateurs peuvent faire cette commande !
  options:
    permission: group.fondateur
    permission-message: §4Tu n'as pas accès à cette commande !
  radio:
  responsable:
    aliases: resp
    permission: oxydia.responsable
    permission-message: §4Seuls les responsables d'équipe peuvent faire cette commande !
  showvanish:
    permission: oxydia.vanish.show
    permission-message: §4Vous n'avez pas accès à cette command
  stafftchat:
    aliases: [ staff, st ]
    permission: oxydia.staff
    permission-message: §4Seuls les staff ont accès à cette commande !
  stagiaire:
    permission: oxydia.stagiaire
    permission-message: §4Seuls les modérateurs stagiaire peuvent faire cette commande !
  test:
  vanish:
    aliases: v
    permission: oxydia.vanish
  worldname:
    aliases: wn
    permission: oxydia.worldname
    permission-message: §4Seul un admin peut éxécuter cette commande !