name: PrincipalPlugin
version: '${version}'
main: fr.silenthill99.principalplugin.Main
api-version: 1.16
authors: [ silenthill99 ]

depend: [ Vault ]

softdepend: [ LuckPerms ]

commands:
  administrateur:
    aliases: admin
    permission: oxydia.admin
    permission-message: §4Seul les administrateurs peuvent faire cette commande !
  builder:
    permission: oxydia.builder
    permission-message: §4Seuls les builders peuvent faire cette commande !
  developpeur:
    aliases: dev
    permission: oxydia.developpeu
    permission-message: §4Seuls les développeurs peuvent faire cette commande !
  hrp:
  logs:
    permission: group.modo-stagiaire
  menu:
    permission: group.modo-stagiaire
    permission-message: §4Vous n'avez pas accès à ceci !
  moderateur:
    aliases: modo
    permission: oxydia.modo
    permission-message: §4Seuls les modérateurs peuvent faire cette commande !
  options:
    permission: group.fondateur
    permission-message: §4Tu n'as pas accès à cette commande !
  radio:
  setspawn:
    permission: oxydia.setspawn
  showvanish:
    permission: oxydia.vanish.show
    permission-message: §4Vous n'avez pas accès à cette commande
  spawn:
  stagiaire:
    permission: oxydia.stagiaire
    permission-message: §4Seuls les modérateurs stagiaire peuvent faire cette commande !
  vanish:
    aliases: v
    permission: oxydia.vanish